# Save to 'kind.config.yaml'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches: # for nginx ingress
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts: # this is needed for plex to be able to mount the media from the host machine (either on the internal or external drive). You also need to add this directory to Docker Hub's shared files
  - hostPath: /Users/logan/Desktop/tvShows
    containerPath: /tv
  extraPortMappings:
  - containerPort: 30777
    hostPort: 30777
    listenAddress: "0.0.0.0"
  - containerPort: 30776
    hostPort: 30776
    listenAddress: "0.0.0.0"
  - containerPort: 30775
    hostPort: 30775
    listenAddress: "0.0.0.0"
  - containerPort: 30774
    hostPort: 30774
    listenAddress: "0.0.0.0"
  - containerPort: 30773
    hostPort: 30773
    listenAddress: "0.0.0.0"
  - containerPort: 30772
    hostPort: 30772
    listenAddress: "0.0.0.0"
  - containerPort: 30771
    hostPort: 30771
    listenAddress: "0.0.0.0"
  - containerPort: 30770
    hostPort: 30770
    listenAddress: "0.0.0.0"
  - containerPort: 30769
    hostPort: 30769
    listenAddress: "0.0.0.0"
  - containerPort: 30768
    hostPort: 30768
    listenAddress: "0.0.0.0"
  - containerPort: 80 # For nginx ingress. allow the local host to make requests to the Ingress controller over ports 80
    hostPort: 80
    protocol: TCP
