# Save to 'kind.config.yaml'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30777
    hostPort: 30777
    listenAddress: "0.0.0.0"
  - containerPort: 30776
    hostPort: 30776
    listenAddress: "0.0.0.0"
  - containerPort: 30775
    hostPort: 30775
    listenAddress: "0.0.0.0"
  - containerPort: 30774
    hostPort: 30774
    listenAddress: "0.0.0.0"
