---
apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  namespace: kubernetes-project
data:
  application.yml: |
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
        my-kafka-test:
          properties:
            bootstrap.servers: "http://kafka-service.kubernetes-project.svc.cluster.local:9092"

    micronaut:
      security:
        token:
          jwt:
            signatures:
              secret:
                generator:
                  secret: pleasechangeme
    # micronaut:
    #   application:
    #     name: akhq
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  labels:
    app: akhq
  namespace: kubernetes-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /app/application.yml
            subPath: application.yml
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: akhq-config

---

---
apiVersion: v1
kind: Service
metadata:
  name: akhq
  labels:
    app: akhq
  namespace: kubernetes-project
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30771  # Specify a NodePort value between 30000-32767
  selector:
    app: akhq
---