---
apiVersion: v1
kind: Namespace
metadata:
  name: plexserver
---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plexserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plexserver
spec:
  type: NodePort
  ports:
    - name: pms-web
      port: 32400
      targetPort: 32400
      nodePort: 30772
      protocol: TCP
  selector:
    app: plex
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plexserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
        env:
          - name: TZ
            value: "Etc/UTC"
          - name: PLEX_CLAIM
            value: "claim-ZZWuD89zeU59tkSyuWxG" # Need to go to https://www.plex.tv/claim/ to get this value. This is required for the Plex Media Server to be set up correctly
        volumeMounts:
        # - mountPath: "/Volumes/Elements/movies"
        #   name: plex-vol
        - mountPath: "/tv" # Path inside the container
          name: host-tvshows
      volumes:
      - name: plex-vol
        persistentVolumeClaim:
          claimName: plex-pvc
      - name: host-tvshows
        hostPath:
          path: "/tv"
          type: Directory
---