---
apiVersion: v1
kind: Namespace
metadata:
  name: plexserver
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plexserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plexserver
spec:
  type: NodePort
  ports:
    - name: pms-web
      port: 32400
      targetPort: 32400
      nodePort: 30772
      protocol: TCP
  selector:
    app: plex
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plexserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        ports:
        - containerPort: 32400
        env:
          - name: TZ
            value: "Etc/UTC"
          - name: PLEX_CLAIM
            value: "claim-KkcyLxkDngV2i5wSgrRa"
        volumeMounts:
        - mountPath: "/Volumes/Elements/movies"
          name: plex-vol
      volumes:
      - name: plex-vol
        persistentVolumeClaim:
          claimName: plex-pvc
---